services:
  app:
    container_name: app
    build: .
    depends_on:
      - db

  db:
    image: 'postgres:latest'
    container_name: bank_cont
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - postgres-networks
    volumes:
      - ${PWD}/db-data/:/var/lib/postgresql/data/

networks:
  postgres-networks:
    driver: bridge
